Repository Haidra-Org/AI-Horde-Worker, pull requests merged in 2023-06, with the labels that each got.

#235 fix: already downloaded models now correctly save in webui
  webui.py
Labels: release:patch

#239 fix: capture all other keys than 'models_to_load' in webui
  webui.py
Labels: release:patch

#243 chore: update some of the hardcoded github urls to use haidra-org
  .github/workflows/release.yml
  README.md
  pyproject.toml
  worker/bridge_data/stable_diffusion.py
Labels: release:patch

#244 Terminal UI Fixes
  bridge_alchemy.py
  bridge_scribe.py
  worker/stats.py
  worker/ui.py
  worker/utils/gpuinfo.py
Labels: release:patch

#245 fix: regression in webui with arrays and ram to leave free
  webui.py
Labels: release:patch

#246 fix: increase initial LoRa download time to 900 secs
  worker/bridge_data/stable_diffusion.py
Labels: release:patch

#248 fix: handle `get_all_models()`'s requests.get call to github if network problems occur
  worker/bridge_data/stable_diffusion.py
Labels: release:patch

#250 feat: hordelib to at least v1.5.1
  requirements.txt
Labels: release:patch

#254 fix: don't hard fail if some non-exception failure happens in `download_image_data`
  worker/jobs/poppers.py
Labels: release:patch

#257 fix: future support for image_is_control for controlnet
  worker/jobs/kudos.py
  worker/jobs/stable_diffusion.py
  worker/post_process.py
  worker/ui.py
Labels: release:patch

#260 chore: remove obsolete info from readme
  README.md
Labels: release:patch

#261 chore: temp pin hordelib (to 1.5.x)
  requirements.txt
Labels: release:patch

#262 fix: Various fixes (lora debug messages, rlimit on runpod, model hash mismatch, more)
  bridge_stable_diffusion.py
  pyproject.toml
  requirements.txt
  worker/bridge_data/framework.py
  worker/bridge_data/stable_diffusion.py
  worker/utils/set_envs.py
  worker/workers/stable_diffusion.py
Labels: release:major

#263 fix: stop worker on continued OutOfMemoryError exceptions
  worker/enums.py
  worker/jobs/framework.py
  worker/jobs/stable_diffusion.py
  worker/workers/framework.py
Labels: release:patch

#264 fix: disable `dynamic_models` if `number_of_dynamic_models` not set/is 0
  webui.py
  worker/bridge_data/stable_diffusion.py
Labels: release:patch

#265 fix: different worker type model counts, prevent warning in alchemist
  worker/ui.py
Labels: release:patch

#267 fix: alchemy not working if models corrupt/missing
  bridge_alchemy.py
  bridge_scribe.py
  bridge_stable_diffusion.py
  worker/bridge_data/interrogation.py
Labels: release:patch

#269 fix: VRAM mismanagement band-aid
  requirements.txt
  worker/workers/framework.py
  worker/workers/stable_diffusion.py
Labels: release:patch

#270 feat: run pilot job on start, notify when jobs seem slower than would be expected
  bridgeData_template.yaml
  webui.py
  worker/bridge_data/framework.py
  worker/bridge_data/stable_diffusion.py
  worker/jobs/framework.py
  worker/workers/framework.py
  worker/workers/stable_diffusion.py
Labels: release:minor
