Repository Haidra-Org/AI-Horde-Worker, pull requests merged in 2023-03, with the labels that each got.

#124 CI/CD
  .github/workflows/release.yml
  worker/consts.py
Labels: release:minor

#125 fix: typo on branch name
  .github/workflows/release.yml
Labels: release:major

#121 Terminal UI
  bridgeData_template.yaml
  horde-bridge.cmd
  requirements.txt
  worker/bridge_data/framework.py
  worker/ui.py
  worker/workers/framework.py
Labels: release:minor

#126 fix: terminal ui typo
  worker/ui.py
Labels: release:patch

#128 fix: only allow terminal ui if always_download option is enabled
  worker/workers/framework.py
Labels: release:patch

#129 Switch to pypi
  requirements.txt
Labels: release:patch

#130 fix: terminal ui doesn't read log file.
  worker/ui.py
Labels: release:patch

#133 WebUI Improvements.
  bridge-webui.cmd
  bridgeData_template.py
  webui.py
Labels: release:minor

#134 Fix Linux Terminal Output
  worker/ui.py
Labels: release:patch

#135 Fix kudos per hour always displaying zero
  worker/bridge_data/framework.py
  worker/jobs/stable_diffusion.py
  worker/workers/framework.py
Labels: release:patch

#136 fix: move option to enable terminal UI in web UI
  webui.py
Labels: release:patch

#137 feat: Dark mode Kitchen Theme for WebUI.
  model-stats.py
  webui.css
  webui.py
Labels: release:minor

#138 fix: better image size selector in webui
  webui.py
Labels: release:patch

#139 fix: webui handles missing config file items.
  webui.py
Labels: release:patch

#140 fix: webui more robust handling of missing config values.
  webui.py
Labels: release:patch

#141 fix: corruption/freezes in the terminal ui
  worker/ui.py
Labels: release:patch

#143 fix: cpu load moved to left, adds thread count
  worker/ui.py
Labels: release:patch
